version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    commit-message:
      prefix: "build(root)"
      include: "scope"
    open-pull-requests-limit: 0
