export { default as Fig1StatusTagLight } from "./fig-1-do-use-status-tags-exclusively-to-denote-status.png";
export { default as Fig1StatusTagDark } from "./fig-1-do-use-status-tags-exclusively-to-denote-status-dark.png";
export { default as Fig2StatusTagLight } from "./fig-2-do-not-use-status-tags-for-anything-other-than-denoting-status.png";
export { default as Fig2StatusTagDark } from "./fig-2-do-not-use-status-tags-for-anything-other-than-denoting-status-dark.png";
export { default as Fig3StatusTagLight } from "./fig-3-do-not-use-a-mix-of-primary-and-secondary-status-tags-to-show-the same-statuses-message-within-a-group-of-items.png";
export { default as Fig3StatusTagDark } from "./fig-3-do-not-use-a-mix-of-primary-and-secondary-status-tags-to-show-the same-statuses-message-within-a-group-of-items-dark.png";
export { default as Fig4StatusTagLight } from "./fig-4-do-use-the-correct-status-tag-size-to-match-other-ui-component-sizes.png";
export { default as Fig4StatusTagDark } from "./fig-4-do-use-the-correct-status-tag-size-to-match-other-ui-component-sizes-dark.png";
export { default as Fig5StatusTagLight } from "./fig-5-do-not-mix-sizes-when-using-multiple-ui-components.png";
export { default as Fig5StatusTagDark } from "./fig-5-do-not-mix-sizes-when-using-multiple-ui-components-dark.png";
export { default as Fig6StatusTagLight } from "./fig-6-do-use-adjectives-to-describe-status.png";
export { default as Fig6StatusTagDark } from "./fig-6-do-use-adjectives-to-describe-status-dark.png";
export { default as Fig7StatusTagLight } from "./fig-7-do-not-use-verbs-in-status-tags.png";
export { default as Fig7StatusTagDark } from "./fig-7-do-not-use-verbs-in-status-tags-dark.png";
export { default as Fig8StatusTagLight } from "./fig-8-do-use-relevant-wording-that-supports-the-status-tag-colour.png";
export { default as Fig8StatusTagDark } from "./fig-8-do-use-relevant-wording-that-supports-the-status-tag-colour-dark.png";
export { default as Fig9StatusTagLight } from "./fig-9-do-not-use-wording-which-directly-contrasts-and-or does-not-support-the-status-of-the-tag.png";
export { default as Fig9StatusTagDark } from "./fig-9-do-not-use-wording-which-directly-contrasts-and-or does-not-support-the-status-of-the-tag-dark.png";
export { default as Fig10StatusTagLight } from "./fig-10-avoid-using-long-labels-as-it-will-force-the-text-to-wrap.png";
export { default as Fig10StatusTagDark } from "./fig-10-avoid-using-long-labels-as-it-will-force-the-text-to-wrap-dark.png";
