export { default as Favicon } from "./favicon.svg";
export { default as GCHQLogo } from "./gchq-logo.svg";
export { default as MI5Logo } from "./mi5-logo.svg";
export { default as SISLogo } from "./sis-logo.svg";
export { default as ICDSLogo } from "./icds-logo.svg";
export { default as StackBlitzLogo } from "./stackblitz-logo.svg";
export { default as DesignImage } from "./designers-image.svg";
export { default as DevImage } from "./developers-image.svg";
export { default as TestDarkImage } from "./test-dark-mode-image.svg";
