#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

bash "$(dirname "$0")/email-check.sh"

print Removing Exif data from static files
node $(dirname "$0")/./removeAuthorExif.js

npm run test
npm run prettier

npx lint-staged
