name: Add QA link to issues on successful build

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF#refs/heads/})"
        id: extract_branch

      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            View your branch deployment here: https://literate-parakeet-8e09c632.pages.github.io/branches/${{ steps.extract_branch.outputs.branch }}
