name: Check Versions
permissions: read-all

on:
  repository_dispatch:
    types: design-system-release

jobs:
  ic-design-system-install-comps:
    name: "IC Design System Install Comps"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
        with:
          ref: develop
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 #v3
        with:
          node-version: 16
      - uses: browser-actions/setup-chrome@latest
      - name: Install latest components
        run: |
          DOCS_VERSION=$(npm view @ukic/docs version)
          FONTS_VERSION=$(npm view @ukic/fonts verion)
          REACT_VERSION=$(npm view @ukic/react version)
          WEB_COMPS_VERSION=$(npm view @ukic/web-components version)
          CANARY_DOCS_VERSION=$(npm view @ukic/canary-docs version)
          CANARY_WEB_COMPS_VERSION=$(npm view @ukic/canary-web-components version)
          CANARY_REACT_VERSION=$(npm view @ukic/canary-react version)
          npm install @ukic/docs@$DOCS_VERSION @ukic/fonts@$FONTS_VERSION @ukic/react@$REACT_VERSION @ukic/web-components@$WEB_COMPS_VERSION @ukic/canary-docs@$CANARY_DOCS_VERSION @ukic/canary-react@$CANARY_REACT_VERSION @ukic/canary-web-components@$CANARY_WEB_COMPS_VERSION
      - name: Create check-versions Pull Request
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 #v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "check-versions -> develop"
          commit-message: "chore(root): Update to latest versions"
          body: "Github action updated package versions"
          branch: check-versions
          base: develop
