name: Prevent PRs to main

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v2.1
        with:
          target: main
          exclude: develop # Don't prevent going from develop -> main
