name: Prevent PRs to main
permissions: read-all

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: Vankka/pr-target-branch-action@def32ec9d93514138d6ac0132ee62e120a72aed5 #v2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: main
          exclude: develop # Don't prevent going from develop -> main
          change-to: develop
          comment: |
            Your PR was set to target `main`, PRs should be target `develop`
            The base branch of this PR has been automatically changed to `develop`, please check that there are no merge conflicts
