name: Release V2
permissions: read-all

on:
  pull_request:
    branches:
      - v2.0.0/develop
    types: [closed]

jobs:
  create-pr:
    if: github.event.pull_request.head.ref == 'check-versions-v2' && github.event.pull_request.merged == true
    name: "Create PR"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 #v3
        with:
          node-version: 18
      - uses: browser-actions/setup-chrome@latest
      - name: Create v2 develop -> v2 main PR
        run: |
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/mi6/ic-design-system/pulls" -d '{"title":"V2 Develop -> V2 Main","body":"Latest updates with latest package versions","head":"v2.0.0/develop","base":"v2.0.0/main"}'
