name: Release
permissions: read-all

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  create-pr:
    if: github.event.pull_request.head.ref == 'update-roadmap' && github.event.pull_request.merged == true
    name: "Create PR"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - uses: browser-actions/setup-chrome@latest
      - name: Create develop -> main PR
        run: |
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/mi6/ic-design-system/pulls" -d '{"title":"Develop -> Main","body":"Latest updates with latest package versions","head":"develop","base":"main"}'
