name: Update Roadmap
permissions: read-all

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type UPDATE to confirm"
        required: true
  repository_dispatch:
    types: design-system-roadmap-update

jobs:
  ic-design-system-install-comps:
    if: >
        github.event_name == 'repository_dispatch' ||
        (github.event_name == 'workflow_dispatch' &&
         github.event.inputs.confirm == 'UPDATE')
    name: "IC Design System Install Comps"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3
        with:
          ref: develop
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 #v3
        with:
          node-version: 16
      - uses: browser-actions/setup-chrome@latest
      - name: Update Roadmap
        run: |
          node updateRoadmap.js
      - name: Create update-roadmap Pull Request
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 #v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "update-roadmap -> develop"
          commit-message: "chore(root): Update roadmap"
          body: "Github action updated roadmap"
          branch: update-roadmap
          base: develop
